name: lint

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: "pip"

      - run: pip install -e '.[dev]'

      - uses: trim21/actions/pre-commit@master

  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: '18'
          check-path: 'src'
