name: lint

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: "pip"

      - run: pip install -r requirements.txt

      - uses: trim21/actions/pre-commit@master
