name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/_build_wheels.yaml

  upload_all:
    name: Upload wheels to PyPI
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheel
          path: dist

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: pipx run twine upload dist/* --disable-progress-bar
        env:
          TWINE_USERNAME: '__token__'
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
